/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/_layout'
import { Route as ProtectedLayoutDyadsIndexRouteImport } from './routes/_protected/_layout.dyads/index'
import { Route as ProtectedLayoutDataIndexRouteImport } from './routes/_protected/_layout.data/index'
import { Route as ProtectedLayoutDyadsListRouteImport } from './routes/_protected/_layout.dyads/list'
import { Route as ProtectedLayoutDyadsDyadIdIndexRouteImport } from './routes/_protected/_layout.dyads/$dyadId/index'
import { Route as ProtectedLayoutDyadsDyadIdJournalEntriesIndexRouteImport } from './routes/_protected/_layout.dyads/$dyadId/journal-entries/index'
import { Route as ProtectedLayoutDyadsDyadIdJournalEntriesJournalEntryIdRouteImport } from './routes/_protected/_layout.dyads/$dyadId/journal-entries/$journalEntryId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/_protected/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protected/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutDyadsIndexRoute =
  ProtectedLayoutDyadsIndexRouteImport.update({
    id: '/dyads/',
    path: '/dyads/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDataIndexRoute =
  ProtectedLayoutDataIndexRouteImport.update({
    id: '/data/',
    path: '/data/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDyadsListRoute =
  ProtectedLayoutDyadsListRouteImport.update({
    id: '/dyads/list',
    path: '/dyads/list',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDyadsDyadIdIndexRoute =
  ProtectedLayoutDyadsDyadIdIndexRouteImport.update({
    id: '/dyads/$dyadId/',
    path: '/dyads/$dyadId/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDyadsDyadIdJournalEntriesIndexRoute =
  ProtectedLayoutDyadsDyadIdJournalEntriesIndexRouteImport.update({
    id: '/dyads/$dyadId/journal-entries/',
    path: '/dyads/$dyadId/journal-entries/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDyadsDyadIdJournalEntriesJournalEntryIdRoute =
  ProtectedLayoutDyadsDyadIdJournalEntriesJournalEntryIdRouteImport.update({
    id: '/dyads/$dyadId/journal-entries/$journalEntryId',
    path: '/dyads/$dyadId/journal-entries/$journalEntryId',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/signin': typeof SigninRoute
  '/': typeof ProtectedIndexRoute
  '/dyads/list': typeof ProtectedLayoutDyadsListRoute
  '/data': typeof ProtectedLayoutDataIndexRoute
  '/dyads': typeof ProtectedLayoutDyadsIndexRoute
  '/dyads/$dyadId': typeof ProtectedLayoutDyadsDyadIdIndexRoute
  '/dyads/$dyadId/journal-entries/$journalEntryId': typeof ProtectedLayoutDyadsDyadIdJournalEntriesJournalEntryIdRoute
  '/dyads/$dyadId/journal-entries': typeof ProtectedLayoutDyadsDyadIdJournalEntriesIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/': typeof ProtectedIndexRoute
  '/dyads/list': typeof ProtectedLayoutDyadsListRoute
  '/data': typeof ProtectedLayoutDataIndexRoute
  '/dyads': typeof ProtectedLayoutDyadsIndexRoute
  '/dyads/$dyadId': typeof ProtectedLayoutDyadsDyadIdIndexRoute
  '/dyads/$dyadId/journal-entries/$journalEntryId': typeof ProtectedLayoutDyadsDyadIdJournalEntriesJournalEntryIdRoute
  '/dyads/$dyadId/journal-entries': typeof ProtectedLayoutDyadsDyadIdJournalEntriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/signin': typeof SigninRoute
  '/_protected/_layout': typeof ProtectedLayoutRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/_layout/dyads/list': typeof ProtectedLayoutDyadsListRoute
  '/_protected/_layout/data/': typeof ProtectedLayoutDataIndexRoute
  '/_protected/_layout/dyads/': typeof ProtectedLayoutDyadsIndexRoute
  '/_protected/_layout/dyads/$dyadId/': typeof ProtectedLayoutDyadsDyadIdIndexRoute
  '/_protected/_layout/dyads/$dyadId/journal-entries/$journalEntryId': typeof ProtectedLayoutDyadsDyadIdJournalEntriesJournalEntryIdRoute
  '/_protected/_layout/dyads/$dyadId/journal-entries/': typeof ProtectedLayoutDyadsDyadIdJournalEntriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/'
    | '/dyads/list'
    | '/data'
    | '/dyads'
    | '/dyads/$dyadId'
    | '/dyads/$dyadId/journal-entries/$journalEntryId'
    | '/dyads/$dyadId/journal-entries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/'
    | '/dyads/list'
    | '/data'
    | '/dyads'
    | '/dyads/$dyadId'
    | '/dyads/$dyadId/journal-entries/$journalEntryId'
    | '/dyads/$dyadId/journal-entries'
  id:
    | '__root__'
    | '/signin'
    | '/_protected/_layout'
    | '/_protected/'
    | '/_protected/_layout/dyads/list'
    | '/_protected/_layout/data/'
    | '/_protected/_layout/dyads/'
    | '/_protected/_layout/dyads/$dyadId/'
    | '/_protected/_layout/dyads/$dyadId/journal-entries/$journalEntryId'
    | '/_protected/_layout/dyads/$dyadId/journal-entries/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SigninRoute: typeof SigninRoute
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_layout': {
      id: '/_protected/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_layout/dyads/': {
      id: '/_protected/_layout/dyads/'
      path: '/dyads'
      fullPath: '/dyads'
      preLoaderRoute: typeof ProtectedLayoutDyadsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/data/': {
      id: '/_protected/_layout/data/'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof ProtectedLayoutDataIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/dyads/list': {
      id: '/_protected/_layout/dyads/list'
      path: '/dyads/list'
      fullPath: '/dyads/list'
      preLoaderRoute: typeof ProtectedLayoutDyadsListRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/dyads/$dyadId/': {
      id: '/_protected/_layout/dyads/$dyadId/'
      path: '/dyads/$dyadId'
      fullPath: '/dyads/$dyadId'
      preLoaderRoute: typeof ProtectedLayoutDyadsDyadIdIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/dyads/$dyadId/journal-entries/': {
      id: '/_protected/_layout/dyads/$dyadId/journal-entries/'
      path: '/dyads/$dyadId/journal-entries'
      fullPath: '/dyads/$dyadId/journal-entries'
      preLoaderRoute: typeof ProtectedLayoutDyadsDyadIdJournalEntriesIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/dyads/$dyadId/journal-entries/$journalEntryId': {
      id: '/_protected/_layout/dyads/$dyadId/journal-entries/$journalEntryId'
      path: '/dyads/$dyadId/journal-entries/$journalEntryId'
      fullPath: '/dyads/$dyadId/journal-entries/$journalEntryId'
      preLoaderRoute: typeof ProtectedLayoutDyadsDyadIdJournalEntriesJournalEntryIdRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
  }
}

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutDyadsListRoute: typeof ProtectedLayoutDyadsListRoute
  ProtectedLayoutDataIndexRoute: typeof ProtectedLayoutDataIndexRoute
  ProtectedLayoutDyadsIndexRoute: typeof ProtectedLayoutDyadsIndexRoute
  ProtectedLayoutDyadsDyadIdIndexRoute: typeof ProtectedLayoutDyadsDyadIdIndexRoute
  ProtectedLayoutDyadsDyadIdJournalEntriesJournalEntryIdRoute: typeof ProtectedLayoutDyadsDyadIdJournalEntriesJournalEntryIdRoute
  ProtectedLayoutDyadsDyadIdJournalEntriesIndexRoute: typeof ProtectedLayoutDyadsDyadIdJournalEntriesIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutDyadsListRoute: ProtectedLayoutDyadsListRoute,
  ProtectedLayoutDataIndexRoute: ProtectedLayoutDataIndexRoute,
  ProtectedLayoutDyadsIndexRoute: ProtectedLayoutDyadsIndexRoute,
  ProtectedLayoutDyadsDyadIdIndexRoute: ProtectedLayoutDyadsDyadIdIndexRoute,
  ProtectedLayoutDyadsDyadIdJournalEntriesJournalEntryIdRoute:
    ProtectedLayoutDyadsDyadIdJournalEntriesJournalEntryIdRoute,
  ProtectedLayoutDyadsDyadIdJournalEntriesIndexRoute:
    ProtectedLayoutDyadsDyadIdJournalEntriesIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SigninRoute: SigninRoute,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  ProtectedIndexRoute: ProtectedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
