/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedTabletComicChatbotRouteImport } from './routes/_protected/tablet-comic-chatbot'
import { Route as ProtectedTabletRouteImport } from './routes/_protected/tablet'
import { Route as ProtectedComicChatbotRouteImport } from './routes/_protected/comic-chatbot'
import { Route as ProtectedComicRouteImport } from './routes/_protected/comic'
import { Route as ProtectedLayoutRouteImport } from './routes/_protected/_layout'
import { Route as ProtectedLayoutDyadsIndexRouteImport } from './routes/_protected/_layout.dyads.index'
import { Route as ProtectedLayoutDyadsListRouteImport } from './routes/_protected/_layout.dyads.list'
import { Route as ProtectedLayoutDyadsDyadIdIndexRouteImport } from './routes/_protected/_layout.dyads.$dyadId.index'
import { Route as ProtectedLayoutDyadsDyadIdJournalIndexRouteImport } from './routes/_protected/_layout.dyads.$dyadId.journal.index'
import { Route as ProtectedLayoutDyadsDyadIdJournalJournalIdRouteImport } from './routes/_protected/_layout.dyads.$dyadId.journal.$journalId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/_protected/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTabletComicChatbotRoute =
  ProtectedTabletComicChatbotRouteImport.update({
    id: '/_protected/tablet-comic-chatbot',
    path: '/tablet-comic-chatbot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProtectedTabletRoute = ProtectedTabletRouteImport.update({
  id: '/_protected/tablet',
  path: '/tablet',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedComicChatbotRoute = ProtectedComicChatbotRouteImport.update({
  id: '/_protected/comic-chatbot',
  path: '/comic-chatbot',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedComicRoute = ProtectedComicRouteImport.update({
  id: '/_protected/comic',
  path: '/comic',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protected/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutDyadsIndexRoute =
  ProtectedLayoutDyadsIndexRouteImport.update({
    id: '/dyads/',
    path: '/dyads/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDyadsListRoute =
  ProtectedLayoutDyadsListRouteImport.update({
    id: '/dyads/list',
    path: '/dyads/list',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDyadsDyadIdIndexRoute =
  ProtectedLayoutDyadsDyadIdIndexRouteImport.update({
    id: '/dyads/$dyadId/',
    path: '/dyads/$dyadId/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDyadsDyadIdJournalIndexRoute =
  ProtectedLayoutDyadsDyadIdJournalIndexRouteImport.update({
    id: '/dyads/$dyadId/journal/',
    path: '/dyads/$dyadId/journal/',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)
const ProtectedLayoutDyadsDyadIdJournalJournalIdRoute =
  ProtectedLayoutDyadsDyadIdJournalJournalIdRouteImport.update({
    id: '/dyads/$dyadId/journal/$journalId',
    path: '/dyads/$dyadId/journal/$journalId',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/signin': typeof SigninRoute
  '/comic': typeof ProtectedComicRoute
  '/comic-chatbot': typeof ProtectedComicChatbotRoute
  '/tablet': typeof ProtectedTabletRoute
  '/tablet-comic-chatbot': typeof ProtectedTabletComicChatbotRoute
  '/': typeof ProtectedIndexRoute
  '/dyads/list': typeof ProtectedLayoutDyadsListRoute
  '/dyads': typeof ProtectedLayoutDyadsIndexRoute
  '/dyads/$dyadId': typeof ProtectedLayoutDyadsDyadIdIndexRoute
  '/dyads/$dyadId/journal/$journalId': typeof ProtectedLayoutDyadsDyadIdJournalJournalIdRoute
  '/dyads/$dyadId/journal': typeof ProtectedLayoutDyadsDyadIdJournalIndexRoute
}
export interface FileRoutesByTo {
  '/signin': typeof SigninRoute
  '/comic': typeof ProtectedComicRoute
  '/comic-chatbot': typeof ProtectedComicChatbotRoute
  '/tablet': typeof ProtectedTabletRoute
  '/tablet-comic-chatbot': typeof ProtectedTabletComicChatbotRoute
  '/': typeof ProtectedIndexRoute
  '/dyads/list': typeof ProtectedLayoutDyadsListRoute
  '/dyads': typeof ProtectedLayoutDyadsIndexRoute
  '/dyads/$dyadId': typeof ProtectedLayoutDyadsDyadIdIndexRoute
  '/dyads/$dyadId/journal/$journalId': typeof ProtectedLayoutDyadsDyadIdJournalJournalIdRoute
  '/dyads/$dyadId/journal': typeof ProtectedLayoutDyadsDyadIdJournalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/signin': typeof SigninRoute
  '/_protected/_layout': typeof ProtectedLayoutRouteWithChildren
  '/_protected/comic': typeof ProtectedComicRoute
  '/_protected/comic-chatbot': typeof ProtectedComicChatbotRoute
  '/_protected/tablet': typeof ProtectedTabletRoute
  '/_protected/tablet-comic-chatbot': typeof ProtectedTabletComicChatbotRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/_layout/dyads/list': typeof ProtectedLayoutDyadsListRoute
  '/_protected/_layout/dyads/': typeof ProtectedLayoutDyadsIndexRoute
  '/_protected/_layout/dyads/$dyadId/': typeof ProtectedLayoutDyadsDyadIdIndexRoute
  '/_protected/_layout/dyads/$dyadId/journal/$journalId': typeof ProtectedLayoutDyadsDyadIdJournalJournalIdRoute
  '/_protected/_layout/dyads/$dyadId/journal/': typeof ProtectedLayoutDyadsDyadIdJournalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/signin'
    | '/comic'
    | '/comic-chatbot'
    | '/tablet'
    | '/tablet-comic-chatbot'
    | '/'
    | '/dyads/list'
    | '/dyads'
    | '/dyads/$dyadId'
    | '/dyads/$dyadId/journal/$journalId'
    | '/dyads/$dyadId/journal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/signin'
    | '/comic'
    | '/comic-chatbot'
    | '/tablet'
    | '/tablet-comic-chatbot'
    | '/'
    | '/dyads/list'
    | '/dyads'
    | '/dyads/$dyadId'
    | '/dyads/$dyadId/journal/$journalId'
    | '/dyads/$dyadId/journal'
  id:
    | '__root__'
    | '/signin'
    | '/_protected/_layout'
    | '/_protected/comic'
    | '/_protected/comic-chatbot'
    | '/_protected/tablet'
    | '/_protected/tablet-comic-chatbot'
    | '/_protected/'
    | '/_protected/_layout/dyads/list'
    | '/_protected/_layout/dyads/'
    | '/_protected/_layout/dyads/$dyadId/'
    | '/_protected/_layout/dyads/$dyadId/journal/$journalId'
    | '/_protected/_layout/dyads/$dyadId/journal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SigninRoute: typeof SigninRoute
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  ProtectedComicRoute: typeof ProtectedComicRoute
  ProtectedComicChatbotRoute: typeof ProtectedComicChatbotRoute
  ProtectedTabletRoute: typeof ProtectedTabletRoute
  ProtectedTabletComicChatbotRoute: typeof ProtectedTabletComicChatbotRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tablet-comic-chatbot': {
      id: '/_protected/tablet-comic-chatbot'
      path: '/tablet-comic-chatbot'
      fullPath: '/tablet-comic-chatbot'
      preLoaderRoute: typeof ProtectedTabletComicChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/tablet': {
      id: '/_protected/tablet'
      path: '/tablet'
      fullPath: '/tablet'
      preLoaderRoute: typeof ProtectedTabletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/comic-chatbot': {
      id: '/_protected/comic-chatbot'
      path: '/comic-chatbot'
      fullPath: '/comic-chatbot'
      preLoaderRoute: typeof ProtectedComicChatbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/comic': {
      id: '/_protected/comic'
      path: '/comic'
      fullPath: '/comic'
      preLoaderRoute: typeof ProtectedComicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_layout': {
      id: '/_protected/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_layout/dyads/': {
      id: '/_protected/_layout/dyads/'
      path: '/dyads'
      fullPath: '/dyads'
      preLoaderRoute: typeof ProtectedLayoutDyadsIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/dyads/list': {
      id: '/_protected/_layout/dyads/list'
      path: '/dyads/list'
      fullPath: '/dyads/list'
      preLoaderRoute: typeof ProtectedLayoutDyadsListRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/dyads/$dyadId/': {
      id: '/_protected/_layout/dyads/$dyadId/'
      path: '/dyads/$dyadId'
      fullPath: '/dyads/$dyadId'
      preLoaderRoute: typeof ProtectedLayoutDyadsDyadIdIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/dyads/$dyadId/journal/': {
      id: '/_protected/_layout/dyads/$dyadId/journal/'
      path: '/dyads/$dyadId/journal'
      fullPath: '/dyads/$dyadId/journal'
      preLoaderRoute: typeof ProtectedLayoutDyadsDyadIdJournalIndexRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protected/_layout/dyads/$dyadId/journal/$journalId': {
      id: '/_protected/_layout/dyads/$dyadId/journal/$journalId'
      path: '/dyads/$dyadId/journal/$journalId'
      fullPath: '/dyads/$dyadId/journal/$journalId'
      preLoaderRoute: typeof ProtectedLayoutDyadsDyadIdJournalJournalIdRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
  }
}

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutDyadsListRoute: typeof ProtectedLayoutDyadsListRoute
  ProtectedLayoutDyadsIndexRoute: typeof ProtectedLayoutDyadsIndexRoute
  ProtectedLayoutDyadsDyadIdIndexRoute: typeof ProtectedLayoutDyadsDyadIdIndexRoute
  ProtectedLayoutDyadsDyadIdJournalJournalIdRoute: typeof ProtectedLayoutDyadsDyadIdJournalJournalIdRoute
  ProtectedLayoutDyadsDyadIdJournalIndexRoute: typeof ProtectedLayoutDyadsDyadIdJournalIndexRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutDyadsListRoute: ProtectedLayoutDyadsListRoute,
  ProtectedLayoutDyadsIndexRoute: ProtectedLayoutDyadsIndexRoute,
  ProtectedLayoutDyadsDyadIdIndexRoute: ProtectedLayoutDyadsDyadIdIndexRoute,
  ProtectedLayoutDyadsDyadIdJournalJournalIdRoute:
    ProtectedLayoutDyadsDyadIdJournalJournalIdRoute,
  ProtectedLayoutDyadsDyadIdJournalIndexRoute:
    ProtectedLayoutDyadsDyadIdJournalIndexRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SigninRoute: SigninRoute,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  ProtectedComicRoute: ProtectedComicRoute,
  ProtectedComicChatbotRoute: ProtectedComicChatbotRoute,
  ProtectedTabletRoute: ProtectedTabletRoute,
  ProtectedTabletComicChatbotRoute: ProtectedTabletComicChatbotRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
